################################################## PROJECT SETTINGS ###################################################

prj:
  pre: # PREPROCESSORS -----------------------------------------------------------------------------------------------
    html:         ''
    css:          sass
    js:           babel

  preOpt: # PREPROCESSORS OPTIONS ------------------------------------------------------------------------------------
    sass:
      outputStyle: 'compressed'
    babel:
      presets:    [es2015]

  mcbw: # BUILT FILES SETTINGS -----------------------------------------------------------------------------------------
      # ----min--clean-build-watch
      html: [1,    1,    1,    1]
      css:  [1,    1,    1,    1]
      js:   [1,    1,    1,    1]
      svg:  [1,    1,    0,    0]
      img:  [1,    0,    0,    0]

################################################## PLUGINS SETTINGS ###################################################

plg:
  htmlmin:
    collapseWhitespace: true

  cleanCss:
    compatibility: 'ie8'

  uglify:

  svgmin:
    js2svg:
#      pretty: true
    plugins:
#      - removeDoctype: false
#      - removeComments: false
#      - cleanupNumericValues:
#          floatPrecision: 2
#      - convertColors:
#          names2hex: false
#          rgb2hex: false

  imagemin:
    progressive: true
    svgoPlugins:
      - removeViewBox: false
#    use: imageminPngquant()
    interlaced: true


  svgstore:
    inlineSvg: true

  del: # DELETE SETTINGS ---------------------------------------------------------------------------------------------
#    force:        true # allow deleting the current working directory and files/folders outside it
#    dryRun:       true # see what would be deleted

  autoprefixer: # VENDOR PREFIX AUTO ADDING SETTINGS -----------------------------------------------------------------
    browsers:     [last 2 versions, safari 5, ie 8, ie 9, opera 12.1, ios 6, android 4]
    cascade:      false

  browserSync: # SERVER STARTING AND BROWSER SYNCHRONIZATION ---------------------------------------------------------
    server:
      baseDir:    'build/'
  #    index:      public.html
  #    directory:  true
  #  tunnel:       true
  #  host:         myhost
  #  port:         9000
  #  proxy:        yourlocal.dev
    logPrefix:    BROWSER

################################################ DIRECTORIES SETTINGS #################################################

dir:
  dest: # DESTINATION DIRECTORIES FOR BUILT FILES --------------------------------------------------------------------
    html:         'build/'
    css:          'build/css/'
    js:           'build/js/'
    svg:          'build/img/inline'
    img:          'build/img/'
    srcMap:       'maps/'

  src: # DIRECTORIES OF SOURCE FILES FOR BUILDING --------------------------------------------------------------------
    html:         'src/templates/**/*.html'
    css:          'src/css/style.scss'
    js:           'src/js/**/*.js'
    svg:          'src/img/inline/**/*.svg'
    img:          ['src/img/**/*.*', '!src/img/inline/**']

  # will use src directories when commented
  watch: # DIRECTORIES OF FILES FOR WATCHING -------------------------------------------------------------------------
#    html:         'src/templates/**/index.html'
    css:          'src/css/**/*.scss'
#    js:           'src/js/**/main.js'
